wb-2207: wb-mqtt-gpio v2.8.4->2.8.4-wb100
wirenboard/wb-releases pull request #239
Opened 2022-10-28 12:45 UTC by vdromanov

надо бекпортировать новую фильтрацию дребезга в 2207

2022-11-01 06:48 UTC, webconn approved these changes

2022-11-01 06:49 UTC, webconn requested changes

2022-11-01 06:49 UTC, webconn commented on releases.yaml
> +            wb-mqtt-gpio: 2.8.4-wb100
У wb-homa-gpio тоже лучше апнуть версию для консистентности

2022-11-02 07:19 UTC, vdromanov commented on releases.yaml
> +            wb-mqtt-gpio: 2.8.4-wb100
готово!

2022-11-02 07:20 UTC, webconn approved these changes

2022-11-02 07:22 UTC, merged