wb-2201: modems_rework (new kernel, hwconf, utils, dt-overlays)
wirenboard/wb-releases pull request #87
Opened 2022-02-24 13:46 UTC by vdromanov

эпопея с модемами кончилась

2022-02-24 21:07 UTC, webconn commented
Есть смысл сейчас эти изменения применить только к WB7, я считаю

2022-02-25 08:24 UTC, vdromanov commented
@webconn как на синке обсуждали - модемы заехали в стейбл только для wb7

2022-03-02 06:47 UTC, webconn approved these changes

2022-03-02 14:46 UTC, webconn commented
Ставлю пока на паузу, ждём починки тестов

2022-03-02 14:46 UTC, webconn requested changes
Ждём тестов

2022-03-04 07:06 UTC, webconn approved these changes

2022-03-04 07:07 UTC, webconn commented
Производство приостановлено пока, к началу надеемся доделать тесты, модемы пусть уходят в релиз в обкатку

2022-03-04 07:07 UTC, merged